# -*- coding: utf-8 -*-
"""Seed deterministic mock-GSC data for the action-seo-test Shopify sandbox.

Creates a second site_config row (idempotent by domain, UUID generated by the
DB), seeds pages from the live catalogue (or an embedded snapshot offline),
builds keyword clusters + SERP snapshots, generates 64 days of deterministic
GSC search_performance rows ending at the fixture anchor, then runs the REAL
pipeline jobs (sync_catalogue_coverage, sync_page_query_match_scores,
run_candidate_generation) so Gate 1 metrics are produced by production code,
not fabricated rows.

Usage:
  python scripts/seed_actionseo_gsc.py --reference-date 2026-09-10 --skip-agent

Optional env:
  SHOPIFY_ACCESS_TOKEN (or SEED_SHOPIFY_TOKEN) -> live catalogue fetch
  (bare shop handle action-seo-test; the adapter appends .myshopify.com)
"""
import argparse
import json
import math
import os
import random
import sys
import urllib.request
from datetime import date, timedelta

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "src"))

import env as env_loader
env_loader.load_env_file(quiet=True)

import db as database  # noqa: E402
from connectors.url_normalize import canonicalize_url  # noqa: E402
from connectors.sync import (  # noqa: E402
    sync_catalogue_coverage,
    sync_page_query_match_scores,
    sync_pages_from_shopify,
)
from generators.orchestrator import run_candidate_generation  # noqa: E402

DOMAIN = "action-seo-test.myshopify.com"
SHOP_HANDLE = "action-seo-test"
SITE_NAME = "ActionSEO Dev"
WINDOW_DAYS = 63
DEVICES = ("MOBILE", "DESKTOP")
MOBILE_SHARE = 0.72
CTR_CURVE_K = 0.30
CTR_CURVE_EXP = 0.9


class CatalogueAdapter:
    """Minimal adapter contract (fetch) serving pre-normalized catalogue rows."""

    def __init__(self, products, collections):
        self._data = {"products": products, "collections": collections}

    def fetch(self, capability, params):
        if capability in self._data:
            return {"ok": True, "data": self._data[capability]}
        return {"ok": False, "capability": capability, "error": "unsupported_capability"}


def _v(vid, price, iq):
    return {"variant_id": vid, "sku": None, "price": price, "inventory_quantity": iq}


def offline_products():
    specs = [
        ("gift-card", "Gift Card", "giftcard", "active", "", 0),
        ("selling-plans-ski-wax", "Selling Plans Ski Wax", "accessories", "active",
         "Accessory, Sport, Winter", 30),
        ("the-3p-fulfilled-snowboard", "The 3p Fulfilled Snowboard", "snowboard", "active",
         "Accessory, Sport, Winter", 12),
        ("the-archived-snowboard", "The Archived Snowboard", "snowboard", "archived",
         "Archived, Premium, Snow, Snowboard, Sport, Winter", 8),
        ("the-collection-snowboard-hydrogen", "The Collection Snowboard: Hydrogen",
         "snowboard", "active", "Accessory, Sport, Winter", 6),
        ("the-collection-snowboard-liquid", "The Collection Snowboard: Liquid",
         "snowboard", "active", "Accessory, Sport, Winter", 9),
        ("the-collection-snowboard-oxygen", "The Collection Snowboard: Oxygen",
         "snowboard", "active", "Accessory, Sport, Winter", 4),
        ("the-compare-at-price-snowboard", "The Compare at Price Snowboard",
         "snowboard", "active", "Accessory, Sport, Winter", 11),
        ("the-complete-snowboard", "The Complete Snowboard", "snowboard", "active",
         "Premium, Snow, Snowboard, Sport, Winter", 35),
        ("the-draft-snowboard", "The Draft Snowboard", "snowboard", "draft", "", 5),
        ("the-hidden-snowboard", "The Hidden Snowboard", "snowboard", "active",
         "Premium, Snow, Snowboard, Sport, Winter", 10),
        ("the-inventory-not-tracked-snowboard", "The Inventory Not Tracked Snowboard",
         "snowboard", "active", "Accessory, Sport, Winter", 0),
        ("the-minimal-snowboard", "The Minimal Snowboard", None, "active", "", 3),
        ("the-multi-location-snowboard", "The Multi-location Snowboard", "snowboard",
         "active", "Premium, Snow, Snowboard, Sport, Winter", 14),
        ("the-multi-managed-snowboard", "The Multi-managed Snowboard", "snowboard",
         "active", "Premium, Snow, Snowboard, Sport, Winter", 9),
        ("the-out-of-stock-snowboard", "The Out of Stock Snowboard", "snowboard",
         "active", "Accessory, Sport, Winter", 0),
        ("the-videographer-snowboard", "The Videographer Snowboard", "snowboard",
         "active", "", 5),
    ]
    prices = {
        "gift-card": [10.0, 25.0, 50.0, 100.0],
        "selling-plans-ski-wax": [9.95, 24.95, 49.95],
    }
    products = []
    for i, (handle, title, ptype, status, tags, total_iq) in enumerate(specs):
        variant_prices = prices.get(handle) or [float({
            "the-3p-fulfilled-snowboard": 2629.95, "the-archived-snowboard": 629.95,
            "the-collection-snowboard-hydrogen": 600.0,
            "the-collection-snowboard-liquid": 749.95,
            "the-collection-snowboard-oxygen": 1025.0,
            "the-compare-at-price-snowboard": 785.95,
            "the-complete-snowboard": 699.95, "the-draft-snowboard": 2629.95,
            "the-hidden-snowboard": 749.95,
            "the-inventory-not-tracked-snowboard": 949.95,
            "the-minimal-snowboard": 885.95,
            "the-multi-location-snowboard": 729.95,
            "the-multi-managed-snowboard": 629.95,
            "the-out-of-stock-snowboard": 885.95,
            "the-videographer-snowboard": 885.95,
        }[handle])]
        per_variant = max(1, total_iq // len(variant_prices)) if total_iq else 0
        remainder = total_iq - per_variant * len(variant_prices)
        variants = [_v(9000000000001 + i * 10 + j, p, per_variant + (1 if j < remainder else 0))
                    for j, p in enumerate(variant_prices)]
        products.append({
            "product_id": str(9000000000000 + i), "title": title, "handle": handle,
            "product_type": ptype, "status": status, "tags": tags,
            "total_inventory": total_iq, "in_stock": total_iq > 0, "variants": variants,
        })
    return products


OFFLINE_COLLECTIONS = [
    {"collection_id": "518695190826", "title": "Home page", "handle": "frontpage",
     "collection_type": "custom", "published": True,
     "url": canonicalize_url(f"https://{DOMAIN}/collections/frontpage")},
    {"collection_id": "518695387434", "title": "Hydrogen", "handle": "hydrogen",
     "collection_type": "custom", "published": True,
     "url": canonicalize_url(f"https://{DOMAIN}/collections/hydrogen")},
    {"collection_id": "518695289130", "title": "Automated Collection",
     "handle": "automated-collection", "collection_type": "smart", "published": True,
     "url": canonicalize_url(f"https://{DOMAIN}/collections/automated-collection")},
]


def _live_collections(token):
    out = []
    for path, kind in (("custom_collections.json?limit=250", "custom"),
                       ("smart_collections.json?limit=250", "smart")):
        url = f"https://{DOMAIN}/admin/api/2024-10/{path}"
        req = urllib.request.Request(url)
        req.add_header("X-Shopify-Access-Token", token)
        with urllib.request.urlopen(req, timeout=60) as resp:
            body = json.loads(resp.read().decode("utf-8"))
        key = "custom_collections" if kind == "custom" else "smart_collections"
        for item in body.get(key, []) or []:
            handle = item.get("handle")
            out.append({
                "collection_id": str(item.get("id")), "title": item.get("title"),
                "handle": handle, "collection_type": kind,
                "published": item.get("published_at") is not None,
                "url": canonicalize_url(f"https://{DOMAIN}/collections/{handle}"),
            })
    return out


def resolve_catalogue(offline):
    token = os.environ.get("SHOPIFY_ACCESS_TOKEN") or os.environ.get("SEED_SHOPIFY_TOKEN")
    if token and not offline:
        try:
            from connectors.shopify import get_shopify_adapter
            adapter = get_shopify_adapter(config={
                "shopify.mode": "live", "shopify.domain": SHOP_HANDLE,
                "shopify.access_token": token,
            })
            products = adapter.fetch("products", {})
            if products.get("ok"):
                collections = _live_collections(token)
                print(f"[catalogue] LIVE: {len(products['data'])} products, "
                      f"{len(collections)} collections")
                return CatalogueAdapter(products["data"], collections)
            print(f"[catalogue] live fetch failed ({products.get('error')}); "
                  "falling back to embedded snapshot")
        except Exception as exc:
            print(f"[catalogue] live fetch failed ({exc}); falling back to embedded snapshot")
    else:
        print("[catalogue] no Shopify token (--offline or unset); using embedded snapshot")
    return CatalogueAdapter(offline_products(), OFFLINE_COLLECTIONS)


CLUSTERS = [
    {"primary": "snowboard stomp pad", "volume": 1900, "commercial_value": "high",
     "keywords": ["snowboard stomp pad", "stomp pad for snowboard",
                  "best snowboard stomp pads"]},
    {"primary": "beginner snowboard package", "volume": 2900, "commercial_value": "high",
     "keywords": ["beginner snowboard package", "snowboard packages for beginners",
                  "beginner snowboard bundle"]},
    {"primary": "snowboard wax kit", "volume": 1200, "commercial_value": "medium",
     "keywords": ["snowboard wax kit", "snowboard tuning kit", "snowboard waxing kit"]},
    {"primary": "complete snowboard", "volume": 3600, "commercial_value": "high",
     "keywords": ["complete snowboard", "best complete snowboard 2026",
                  "complete snowboard for beginners"]},
    {"primary": "hydrogen snowboard", "volume": 1700, "commercial_value": "high",
     "keywords": ["hydrogen snowboard", "hydrogen snowboard review",
                  "hydrogen all mountain snowboard"]},
    {"primary": "buy complete snowboard", "volume": 880, "commercial_value": "high",
     "keywords": ["buy complete snowboard", "complete snowboard shop",
                  "complete snowboard for sale"]},
    {"primary": "snowboard gift card", "volume": 640, "commercial_value": "medium",
     "keywords": ["snowboard gift card", "snowboard gift ideas",
                  "snowboard accessories gift"]},
    {"primary": "liquid snowboard", "volume": 540, "commercial_value": "medium",
     "keywords": ["liquid snowboard", "liquid snowboard price",
                  "the collection snowboard liquid"]},
]

COMPETITORS = {
    "snowboard stomp pad": [
        ("https://www.crabgrab.com/collections/stomp-pads", 1),
        ("https://www.dakine.com/collections/stomp-pads", 2),
        ("https://www.the-house.com/stomp-pads", 3),
        ("https://www.evo.com/shop/snowboard-accessories/stomp-pads", 4),
        ("https://www.unionbindingcompany.com/stomp-pads", 6),
    ],
    "beginner snowboard package": [
        ("https://www.the-house.com/beginner-snowboard-packages", 1),
        ("https://www.evo.com/guides/beginner-snowboard-packages", 2),
        ("https://www.rei.com/c/beginner-snowboard-packages", 3),
        ("https://www.whitelines.com/beginner-packages", 5),
    ],
    "snowboard wax kit": [
        ("https://www.dakine.com/collections/snowboard-tuning", 1),
        ("https://www.demonunited.com/pages/snowboard-wax-kits", 2),
        ("https://www.thesalon.com/snowboard-wax-kits", 4),
        ("https://www.evo.com/shop/snowboard-tuning", 6),
    ],
}


def seed_clusters(conn, site_id):
    created = 0
    with conn.cursor() as cur:
        for spec in CLUSTERS:
            cur.execute(
                "SELECT cluster_id FROM keyword_clusters "
                "WHERE site_id = %s AND primary_keyword = %s",
                (str(site_id), spec["primary"]),
            )
            row = cur.fetchone()
            if row:
                cluster_id = row[0]
            else:
                cur.execute(
                    "INSERT INTO keyword_clusters (site_id, primary_keyword, keywords, "
                    "intent, commercial_intent, recommended_page_type, search_volume, "
                    "commercial_value) VALUES (%s, %s, %s, 'commercial', true, 'collection', "
                    "%s, %s) RETURNING cluster_id",
                    (str(site_id), spec["primary"], spec["keywords"],
                     spec["volume"], spec["commercial_value"]),
                )
                cluster_id = cur.fetchone()[0]
                created += 1
            for kw in spec["keywords"]:
                cur.execute(
                    "INSERT INTO cluster_queries (cluster_id, query) VALUES (%s, %s) "
                    "ON CONFLICT (cluster_id, query) DO NOTHING",
                    (str(cluster_id), kw),
                )
    return created


GSC_PAIRS = [
    {"query": "complete snowboard", "path": "/products/the-complete-snowboard",
     "cluster": "complete snowboard", "base_impressions": 140, "pos_base": 6.5,
     "pattern": "flat"},
    {"query": "hydrogen snowboard", "path": "/collections/hydrogen",
     "cluster": "hydrogen snowboard", "base_impressions": 80, "pos_base": 11.2,
     "pattern": "flat"},
    {"query": "buy complete snowboard", "path": "/products/the-complete-snowboard",
     "cluster": "buy complete snowboard", "base_impressions": 60, "pos_base": 3.8,
     "pattern": "low_ctr", "devices": ["DESKTOP"]},
    {"query": "snowboard gift card", "path": "/products/gift-card",
     "cluster": "snowboard gift card", "base_impressions": 90, "pos_base": 4.2,
     "pattern": "click_decline"},
    {"query": "liquid snowboard", "path": "/products/the-collection-snowboard-liquid",
     "cluster": "liquid snowboard", "base_impressions": 70, "pos_base": 4.8,
     "pattern": "rank_decline"},
]


def _base_position(pair, d, ref):
    if pair["pattern"] == "rank_decline":
        if d >= ref - timedelta(days=7):
            return 8.6
        return pair["pos_base"]
    delta = (d - (ref - timedelta(days=WINDOW_DAYS))).days
    return pair["pos_base"] + 0.4 * math.sin(delta / 3.0)


def _base_ctr(pos):
    return min(0.30, CTR_CURVE_K / (max(pos, 1.0) ** CTR_CURVE_EXP))


def seed_search_performance(conn, site_id, ref_date):
    ref = ref_date
    start = ref - timedelta(days=WINDOW_DAYS)
    rows = []
    for pair in GSC_PAIRS:
        page_url = canonicalize_url(f"https://{DOMAIN}{pair['path']}")
        devices = pair.get("devices") or list(DEVICES)
        for device in devices:
            rng = random.Random(f"{DOMAIN}|{pair['query']}|{page_url}|{device}")
            for offset in range(WINDOW_DAYS + 1):
                d = start + timedelta(days=offset)
                weekday = d.weekday()
                wd = 0.85 if weekday >= 5 else 1.0
                share = MOBILE_SHARE if device == "MOBILE" else (1.0 - MOBILE_SHARE)
                impressions = max(1, round(
                    pair["base_impressions"] * share * wd
                    * (1 + rng.uniform(-0.15, 0.15))))
                pos = _base_position(pair, d, ref)
                if device == "MOBILE":
                    pos += 0.2
                if pair["pattern"] == "low_ctr":
                    ctr = rng.uniform(0.010, 0.016)
                else:
                    ctr = min(0.30, CTR_CURVE_K / (max(pos, 1.0) ** CTR_CURVE_EXP))
                    if device == "MOBILE":
                        ctr *= 0.85
                    else:
                        ctr *= 1.10
                    if pair["pattern"] == "click_decline" and d >= ref - timedelta(days=7):
                        ctr *= 0.42
                    ctr *= (1 + rng.uniform(-0.10, 0.10))
                clicks = min(impressions, round(impressions * ctr))
                stored_ctr = round(clicks / impressions, 4) if impressions else 0
                rows.append({
                    "site_id": str(site_id), "date": str(d), "query": pair["query"],
                    "page_url": page_url, "country": "USA", "device": device,
                    "clicks": clicks, "impressions": impressions,
                    "ctr": stored_ctr, "position": round(max(1.0, pos + rng.uniform(-0.3, 0.3)), 2),
                })
    return database.insert_rows(
        conn, "search_performance", rows,
        conflict_target="site_id, date, query, page_url_hash, country, device",
        update_keys=["clicks", "impressions", "ctr", "position"],
    )


def seed_serp_snapshots(conn, site_id, ref_date):
    with conn.cursor() as cur:
        cur.execute(
            "SELECT cluster_id, primary_keyword FROM keyword_clusters WHERE site_id = %s",
            (str(site_id),),
        )
        cluster_by_primary = {pk: cid for cid, pk in cur.fetchall()}
    inserted = 0
    self_row = ("https://action-seo-test.myshopify.com/products/the-complete-snowboard", 7)
    with conn.cursor() as cur:
        for primary, competitors in COMPETITORS.items():
            cluster_id = cluster_by_primary.get(primary)
            if cluster_id is None:
                continue
            for url, position in competitors:
                cur.execute(
                    "INSERT INTO openseo_serp_snapshots (site_id, cluster_id, query, "
                    "result_url, result_domain, position, is_self, snapshot_date) "
                    "VALUES (%s, %s, %s, %s, %s, %s, false, %s) "
                    "ON CONFLICT (site_id, query, result_url, snapshot_date) DO NOTHING",
                    (str(site_id), str(cluster_id), primary, url,
                     url.split("/")[2] if "://" in url else None, position, str(ref_date)),
                )
                inserted += cur.rowcount
        cluster_id = cluster_by_primary.get("complete snowboard")
        if cluster_id is not None:
            url, position = ("https://action-seo-test.myshopify.com/products/the-complete-snowboard", 7)
            cur.execute(
                "INSERT INTO openseo_serp_snapshots (site_id, cluster_id, query, "
                "result_url, result_domain, position, is_self, snapshot_date) "
                "VALUES (%s, %s, %s, %s, %s, %s, true, %s) "
                "ON CONFLICT (site_id, query, result_url, snapshot_date) DO NOTHING",
                (str(site_id), str(cluster_id), "complete snowboard", url,
                 "action-seo-test.myshopify.com", position, str(ref_date)),
            )
            inserted += cur.rowcount
    return inserted


def verify(conn, site_id):
    out = {}
    with conn.cursor() as cur:
        for table in ("pages", "keyword_clusters", "catalogue_coverage",
                      "page_query_match_scores", "openseo_serp_snapshots",
                      "search_performance", "recommendations", "candidate_runs"):
            cur.execute(
                f"SELECT count(*) FROM {table} WHERE site_id = %s",
                (str(site_id),),
            )
            out[f"count_{table}"] = cur.fetchone()[0]
        cur.execute(
            "SELECT count(*) FROM cluster_queries cq "
            "JOIN keyword_clusters kc ON kc.cluster_id = cq.cluster_id "
            "WHERE kc.site_id = %s",
            (str(site_id),),
        )
        out["count_cluster_queries"] = cur.fetchone()[0]
        cur.execute(
            "SELECT page_type, count(*) FROM pages WHERE site_id = %s GROUP BY page_type",
            (str(site_id),),
        )
        out["pages_by_type"] = {r[0]: r[1] for r in cur.fetchall()}
        cur.execute(
            "SELECT count(*) FROM search_performance sp "
            "LEFT JOIN pages p ON p.site_id = sp.site_id AND p.url_hash = sp.page_url_hash "
            "WHERE sp.site_id = %s AND p.page_id IS NULL",
            (str(site_id),),
        )
        out["sp_rows_without_matching_page"] = cur.fetchone()[0]
        cur.execute(
            "SELECT min(date), max(date) FROM search_performance WHERE site_id = %s",
            (str(site_id),),
        )
        out["sp_date_range"] = [str(v) for v in cur.fetchone()]
        cur.execute(
            "SELECT r.generator, r.status, count(*) FROM recommendations r "
            "WHERE r.site_id = %s GROUP BY r.generator, r.status ORDER BY r.generator",
            (str(site_id),),
        )
        out["recommendations_by_generator_status"] = [
            {"generator": r[0], "status": r[1], "count": r[2]} for r in cur.fetchall()]
        cur.execute(
            "SELECT generator, action_type, COALESCE(target_url, proposed_url), "
            "COALESCE(kc.primary_keyword, ''), impact "
            "FROM recommendations r LEFT JOIN keyword_clusters kc "
            "ON kc.cluster_id = r.cluster_id "
            "WHERE r.site_id = %s AND r.status = 'raw' ORDER BY generator",
            (str(site_id),),
        )
        out["raw_candidates"] = [
            {"generator": r[0], "action_type": r[1], "url": r[2],
             "cluster": r[3], "impact": r[4]} for r in cur.fetchall()]
        cur.execute(
            "SELECT generator, candidate_count FROM candidate_runs WHERE site_id = %s "
            "ORDER BY run_at",
            (str(site_id),),
        )
        out["candidate_runs"] = [{"generator": r[0], "candidate_count": r[1]}
                                 for r in cur.fetchall()]
    return out


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--reference-date", default="2026-09-10")
    parser.add_argument("--skip-agent", action="store_true")
    parser.add_argument("--offline", action="store_true",
                        help="skip live Shopify fetch; use embedded catalogue snapshot")
    args = parser.parse_args()
    ref_date = date.fromisoformat(args.reference_date)

    conn = database.get_connection()
    try:
        with conn.cursor() as cur:
            cur.execute("SET TIME ZONE 'UTC'")
            cur.execute(
                "SELECT site_id FROM site_config WHERE domain = %s", (DOMAIN,))
            row = cur.fetchone()
            if row:
                site_id = row[0]
                print(f"[site] existing site_id: {site_id}")
            else:
                cur.execute(
                    "INSERT INTO site_config (site_name, domain, gsc_property, "
                    "shopify_domain, catalogue_size_tier) "
                    "VALUES (%s, %s, %s, %s, 'small') RETURNING site_id",
                    (SITE_NAME, DOMAIN, f"sc-domain:{DOMAIN}", SHOP_HANDLE),
                )
                site_id = cur.fetchone()[0]
                print(f"[site] created site_id: {site_id}")
        conn.commit()

        catalogue = resolve_catalogue(args.offline)
        counts = {"pages": sync_pages_from_shopify(conn, catalogue, site_id, DOMAIN)}
        print(f"[pages] upserted: {counts['pages']}")

        counts["keyword_clusters_created"] = seed_clusters(conn, site_id)
        counts["search_performance_rows"] = seed_search_performance(conn, site_id, ref_date)
        counts["serp_snapshots"] = seed_serp_snapshots(conn, site_id, ref_date)
        conn.commit()
        print(f"[seed] clusters(+{counts['keyword_clusters_created']}), "
              f"search_performance({counts['search_performance_rows']}), "
              f"serp(+{counts['serp_snapshots']})")

        counts["catalogue_coverage"] = sync_catalogue_coverage(
            conn, site_id, DOMAIN, catalogue)
        counts["page_query_match_scores"] = sync_page_query_match_scores(conn, site_id)
        conn.commit()
        print(f"[pipeline] catalogue_coverage={counts['catalogue_coverage']}, "
              f"page_query_match_scores={counts['page_query_match_scores']}")

        gen_counts = run_candidate_generation(
            site_id, conn=conn, reference_date=args.reference_date)
        print(f"[generators] {json.dumps(gen_counts, default=str)}")

        if not args.skip_agent:
            try:
                from agents.seo_agent import run_agent
                summary = run_agent(str(site_id), conn=conn)
                print(f"[agent] {json.dumps(summary, default=str)[:800]}")
            except Exception as exc:
                conn.rollback()
                print(f"[agent] skipped after error: {type(exc).__name__}: {exc}")

        report = verify(conn, site_id)
        report["site_id"] = str(site_id)
        report["reference_date"] = args.reference_date
        report["sync_counts"] = {k: v for k, v in counts.items()}
        print("\n=== GATE 1 REPORT ===")
        print(json.dumps(report, indent=2, default=str))
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


if __name__ == "__main__":
    main()