/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PProjectIdIndexRouteImport } from './routes/p/$projectId/index'
import { Route as PProjectIdActionQueueRouteImport } from './routes/p/$projectId/action-queue'
import { Route as PProjectIdPipelinesRouteImport } from './routes/p/$projectId/pipelines'
import { Route as PProjectIdResultsRouteImport } from './routes/p/$projectId/results'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectIdIndexRoute = PProjectIdIndexRouteImport.update({
  id: '/p/$projectId/',
  path: '/p/$projectId/',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectIdActionQueueRoute = PProjectIdActionQueueRouteImport.update({
  id: '/p/$projectId/action-queue',
  path: '/p/$projectId/action-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectIdPipelinesRoute = PProjectIdPipelinesRouteImport.update({
  id: '/p/$projectId/pipelines',
  path: '/p/$projectId/pipelines',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectIdResultsRoute = PProjectIdResultsRouteImport.update({
  id: '/p/$projectId/results',
  path: '/p/$projectId/results',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/p/$projectId/action-queue': typeof PProjectIdActionQueueRoute
  '/p/$projectId/pipelines': typeof PProjectIdPipelinesRoute
  '/p/$projectId/results': typeof PProjectIdResultsRoute
  '/p/$projectId/': typeof PProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/p/$projectId/action-queue': typeof PProjectIdActionQueueRoute
  '/p/$projectId/pipelines': typeof PProjectIdPipelinesRoute
  '/p/$projectId/results': typeof PProjectIdResultsRoute
  '/p/$projectId': typeof PProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/p/$projectId/action-queue': typeof PProjectIdActionQueueRoute
  '/p/$projectId/pipelines': typeof PProjectIdPipelinesRoute
  '/p/$projectId/results': typeof PProjectIdResultsRoute
  '/p/$projectId/': typeof PProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/p/$projectId/action-queue'
    | '/p/$projectId/pipelines'
    | '/p/$projectId/results'
    | '/p/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/p/$projectId/action-queue'
    | '/p/$projectId/pipelines'
    | '/p/$projectId/results'
    | '/p/$projectId'
  id:
    | '__root__'
    | '/'
    | '/p/$projectId/action-queue'
    | '/p/$projectId/pipelines'
    | '/p/$projectId/results'
    | '/p/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PProjectIdActionQueueRoute: typeof PProjectIdActionQueueRoute
  PProjectIdPipelinesRoute: typeof PProjectIdPipelinesRoute
  PProjectIdResultsRoute: typeof PProjectIdResultsRoute
  PProjectIdIndexRoute: typeof PProjectIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$projectId/': {
      id: '/p/$projectId/'
      path: '/p/$projectId'
      fullPath: '/p/$projectId/'
      preLoaderRoute: typeof PProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$projectId/action-queue': {
      id: '/p/$projectId/action-queue'
      path: '/p/$projectId/action-queue'
      fullPath: '/p/$projectId/action-queue'
      preLoaderRoute: typeof PProjectIdActionQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$projectId/pipelines': {
      id: '/p/$projectId/pipelines'
      path: '/p/$projectId/pipelines'
      fullPath: '/p/$projectId/pipelines'
      preLoaderRoute: typeof PProjectIdPipelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$projectId/results': {
      id: '/p/$projectId/results'
      path: '/p/$projectId/results'
      fullPath: '/p/$projectId/results'
      preLoaderRoute: typeof PProjectIdResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PProjectIdActionQueueRoute: PProjectIdActionQueueRoute,
  PProjectIdPipelinesRoute: PProjectIdPipelinesRoute,
  PProjectIdResultsRoute: PProjectIdResultsRoute,
  PProjectIdIndexRoute: PProjectIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
